using System.Globalization;
using System.Windows;

namespace CryptoLab.App.Services;

public sealed class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _resources = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["app_subtitle"] = "Cryptography Learning & Experimentation Platform",
            ["dashboard"] = "Dashboard",
            ["encrypt_decrypt"] = "Encrypt / Decrypt",
            ["algorithms"] = "Algorithms",
            ["learning"] = "Learning Center",
            ["compare"] = "Compare Algorithms",
            ["history"] = "History",
            ["settings"] = "Settings",
            ["about"] = "About",
            ["ready"] = "Ready",
            ["welcome"] = "Welcome to CryptoLab",
            ["interactive"] = "Interactive Cryptography Learning Environment",
            ["quick_actions"] = "Quick Actions",
            ["start_encryption"] = "Start Encryption",
            ["explore_algorithms"] = "Explore Algorithms",
            ["learn_cryptography"] = "Learn Cryptography",
            ["compare_algorithms"] = "Compare Algorithms",
            ["input_text"] = "Input Text",
            ["output"] = "Output",
            ["select_algorithm"] = "Select Algorithm",
            ["configuration"] = "Configuration",
            ["operation"] = "Operation",
            ["encrypt"] = "Encrypt",
            ["decrypt"] = "Decrypt",
            ["hash"] = "Hash",
            ["copy"] = "Copy",
            ["clear"] = "Clear",
            ["paste"] = "Paste",
            ["load_file"] = "Load File",
            ["save"] = "Save",
            ["export"] = "Export",
            ["visualize"] = "Visualize Algorithm",
            ["how_it_works"] = "How It Works",
            ["educational_notice"] = "Educational Use Only",
            ["empty_history"] = "No operations yet. Start by encrypting a message.",
            ["appearance"] = "Appearance",
            ["language"] = "Language",
            ["general"] = "General",
            ["security"] = "Security",
            ["dark"] = "Dark Mode",
            ["light"] = "Light Mode",
            ["system"] = "System Theme",
            ["auto_clear"] = "Auto-clear input after success",
            ["save_history"] = "Save operation history metadata",
            ["animations"] = "Animation effects",
            ["clear_history"] = "Clear History",
            ["reset_app"] = "Reset Application",
            ["generate_keys"] = "Generate Keys",
            ["status_success"] = "Success",
            ["status_error"] = "Error",

            ["language_english"] = "English",
            ["language_arabic"] = "Arabic",

            ["stat_algorithms"] = "Available Algorithms",
            ["stat_algorithms_sub"] = "Classical, modern, and hash functions",
            ["stat_encryption"] = "Encryption Methods",
            ["stat_encryption_sub"] = "Reversible algorithms",
            ["stat_lessons"] = "Learning Topics",
            ["stat_lessons_sub"] = "Structured lessons",
            ["stat_operations"] = "Operations Performed",
            ["stat_operations_sub"] = "Session metadata only",
            ["dashboard_notice"] = "This application is designed for educational purposes. Demonstration algorithms such as Caesar, ROT13, DES, MD5, and SHA-1 should not be considered secure choices for protecting sensitive data.",

            ["crypto_subtitle"] = "Configure an algorithm, run it, and study the result.",
            ["meta_algorithm"] = "Algorithm",
            ["meta_operation"] = "Operation",
            ["meta_input_length"] = "Input Length",
            ["meta_output_length"] = "Output Length",
            ["meta_time"] = "Execution Time",
            ["meta_encoding"] = "Encoding",
            ["meta_status"] = "Status",
            ["explanation_placeholder"] = "Run an operation to see the educational explanation.",
            ["hashing_note"] = "Hashing is one-way and cannot normally be decrypted.",
            ["no_steps"] = "No visualization steps for this result.",
            ["label_shift"] = "Shift / Key",
            ["label_keyword"] = "Keyword",
            ["label_key_a"] = "Key a",
            ["label_key_b"] = "Key b",
            ["label_rails"] = "Rails",
            ["label_key"] = "Key",
            ["label_mode"] = "Mode",
            ["label_iv"] = "IV / Nonce (optional; random if empty)",
            ["label_key_size"] = "Key Size",
            ["label_public_key"] = "Public Key",
            ["label_private_key"] = "Private Key",
            ["toast_operation_done"] = "Operation completed",
            ["toast_keys_generated"] = "RSA key pair generated",
            ["toast_copied"] = "Result copied to clipboard",
            ["toast_saved"] = "Result saved",
            ["toast_history_cleared"] = "History cleared",

            ["algorithms_title"] = "Cryptography Algorithms",
            ["algorithms_subtitle"] = "Browse algorithm details, security level, and educational guidance.",
            ["label_category"] = "Category",
            ["label_security"] = "Security",
            ["learn_more"] = "Learn More",
            ["try_it"] = "Try It",
            ["hash_it"] = "Hash It",

            ["overview"] = "Overview",
            ["how_it_works_title"] = "How It Works",
            ["math_concept_title"] = "Mathematical Concept",
            ["advantages"] = "Advantages",
            ["security_analysis"] = "Security Analysis",
            ["try_this"] = "Try This Algorithm",
            ["back_to_algorithms"] = "Back to Algorithms",

            ["python_title"] = "Python Implementation",
            ["python_libraries"] = "Libraries Used",
            ["python_functions"] = "Function Reference",
            ["python_code"] = "Source Code (from scratch, no crypto libraries)",
            ["python_verified"] = "Verified against official test vectors — all 33 tests pass.",
            ["copy_code"] = "Copy Code",
            ["toast_code_copied"] = "Python code copied to clipboard",
            ["export_pdf"] = "Export PDF",
            ["toast_pdf_exported"] = "PDF exported successfully",
            ["toast_pdf_failed"] = "PDF export failed",

            ["learning_subtitle"] = "Structured lessons with examples and exercises.",
            ["interactive_exercises"] = "Interactive Exercises",

            ["compare_subtitle"] = "Compare algorithms by type, speed, usage, and security notes.",
            ["select_algorithms"] = "Select Algorithms",
            ["first_algorithm"] = "First Algorithm",
            ["second_algorithm"] = "Second Algorithm",
            ["compare_property"] = "Property",
            ["compare_type"] = "Type",
            ["compare_security"] = "Security",
            ["compare_key_type"] = "Key Type",
            ["compare_main_use"] = "Main Use",
            ["compare_reversible"] = "Reversible",
            ["compare_notice"] = "Notice",
            ["yes"] = "Yes",
            ["no"] = "No",
            ["no_key"] = "No key",

            ["history_title"] = "Operation History",
            ["history_subtitle"] = "Session operation metadata. Sensitive input text is not stored.",
            ["operations"] = "Operations",

            ["settings_subtitle"] = "Control appearance, language, history, and session data.",
            ["security_note"] = "History stores only metadata: timestamp, algorithm, operation, status, lengths, and timing.",

            ["about_tagline"] = "An Interactive Cryptography Learning & Experimentation Platform",
            ["about_version"] = "Version",
            ["about_developer"] = "Developer",
            ["about_technology"] = "Technology",
            ["about_purpose"] = "Educational Purpose",
            ["about_purpose_text"] = "Teach cryptography basics, algorithm behavior, validation, and safe separation between learning demos and production security.",
            ["about_license"] = "License"
        },
        ["ar"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["app_subtitle"] = "منصة تعلم وتجربة التشفير",
            ["dashboard"] = "لوحة التحكم",
            ["encrypt_decrypt"] = "تشفير / فك التشفير",
            ["algorithms"] = "الخوارزميات",
            ["learning"] = "مركز التعلم",
            ["compare"] = "مقارنة الخوارزميات",
            ["history"] = "السجل",
            ["settings"] = "الإعدادات",
            ["about"] = "حول",
            ["ready"] = "جاهز",
            ["welcome"] = "مرحبًا بك في CryptoLab",
            ["interactive"] = "بيئة تفاعلية لتعلم التشفير",
            ["quick_actions"] = "إجراءات سريعة",
            ["start_encryption"] = "ابدأ التشفير",
            ["explore_algorithms"] = "استكشف الخوارزميات",
            ["learn_cryptography"] = "تعلم التشفير",
            ["compare_algorithms"] = "قارن الخوارزميات",
            ["input_text"] = "النص المدخل",
            ["output"] = "الناتج",
            ["select_algorithm"] = "اختر الخوارزمية",
            ["configuration"] = "الإعدادات",
            ["operation"] = "العملية",
            ["encrypt"] = "تشفير",
            ["decrypt"] = "فك التشفير",
            ["hash"] = "هاش",
            ["copy"] = "نسخ",
            ["clear"] = "مسح",
            ["paste"] = "لصق",
            ["load_file"] = "تحميل ملف",
            ["save"] = "حفظ",
            ["export"] = "تصدير",
            ["visualize"] = "عرض خطوات الخوارزمية",
            ["how_it_works"] = "كيف تعمل",
            ["educational_notice"] = "للاستخدام التعليمي فقط",
            ["empty_history"] = "لا توجد عمليات بعد. ابدأ بتشفير رسالة.",
            ["appearance"] = "المظهر",
            ["language"] = "اللغة",
            ["general"] = "عام",
            ["security"] = "الأمان",
            ["dark"] = "الوضع الداكن",
            ["light"] = "الوضع الفاتح",
            ["system"] = "حسب النظام",
            ["auto_clear"] = "مسح الإدخال بعد نجاح العملية",
            ["save_history"] = "حفظ بيانات السجل فقط",
            ["animations"] = "تأثيرات الحركة",
            ["clear_history"] = "مسح السجل",
            ["reset_app"] = "إعادة ضبط التطبيق",
            ["generate_keys"] = "توليد المفاتيح",
            ["status_success"] = "نجاح",
            ["status_error"] = "خطأ",

            ["language_english"] = "الإنجليزية",
            ["language_arabic"] = "العربية",

            ["stat_algorithms"] = "الخوارزميات المتوفرة",
            ["stat_algorithms_sub"] = "خوارزميات كلاسيكية وحديثة ودوال هاش",
            ["stat_encryption"] = "طرق التشفير",
            ["stat_encryption_sub"] = "خوارزميات قابلة للعكس",
            ["stat_lessons"] = "مواضيع التعلم",
            ["stat_lessons_sub"] = "دروس منظّمة",
            ["stat_operations"] = "العمليات المنفذة",
            ["stat_operations_sub"] = "بيانات جلسة فقط",
            ["dashboard_notice"] = "هذا التطبيق مصمم للأغراض التعليمية فقط. خوارزميات العرض مثل Caesar وROT13 وDES وMD5 وSHA-1 يجب ألا تُعتبر خيارات آمنة لحماية البيانات الحساسة.",

            ["crypto_subtitle"] = "اضبط الخوارزمية، نفّذ العملية، وادرس النتيجة بالتفصيل.",
            ["meta_algorithm"] = "الخوارزمية",
            ["meta_operation"] = "العملية",
            ["meta_input_length"] = "طول المدخلات",
            ["meta_output_length"] = "طول المخرجات",
            ["meta_time"] = "زمن التنفيذ",
            ["meta_encoding"] = "الترميز",
            ["meta_status"] = "الحالة",
            ["explanation_placeholder"] = "نفّذ عملية لعرض الشرح التعليمي المفصل.",
            ["hashing_note"] = "الهاش عملية أحادية الاتجاه ولا يمكن عادة فك تشفيرها.",
            ["no_steps"] = "لا توجد خطوات عرض لهذه النتيجة.",
            ["label_shift"] = "الإزاحة / المفتاح",
            ["label_keyword"] = "الكلمة المفتاحية",
            ["label_key_a"] = "المفتاح a",
            ["label_key_b"] = "المفتاح b",
            ["label_rails"] = "عدد المسارات",
            ["label_key"] = "المفتاح",
            ["label_mode"] = "الوضع",
            ["label_iv"] = "IV / Nonce (اختياري؛ عشوائي إذا تُرك فارغًا)",
            ["label_key_size"] = "حجم المفتاح",
            ["label_public_key"] = "المفتاح العام",
            ["label_private_key"] = "المفتاح الخاص",
            ["toast_operation_done"] = "اكتملت العملية",
            ["toast_keys_generated"] = "تم توليد زوج مفاتيح RSA",
            ["toast_copied"] = "تم نسخ النتيجة إلى الحافظة",
            ["toast_saved"] = "تم حفظ النتيجة",
            ["toast_history_cleared"] = "تم مسح السجل",

            ["algorithms_title"] = "خوارزميات التشفير",
            ["algorithms_subtitle"] = "تصفح تفاصيل الخوارزميات ومستوى أمانها والإرشادات التعليمية.",
            ["label_category"] = "الفئة",
            ["label_security"] = "مستوى الأمان",
            ["learn_more"] = "اعرف المزيد",
            ["try_it"] = "جرّبها",
            ["hash_it"] = "نفّذ الهاش",

            ["overview"] = "نظرة عامة",
            ["how_it_works_title"] = "كيف تعمل",
            ["math_concept_title"] = "المفهوم الرياضي",
            ["advantages"] = "المزايا",
            ["security_analysis"] = "تحليل الأمان",
            ["try_this"] = "جرّب هذه الخوارزمية",
            ["back_to_algorithms"] = "العودة إلى الخوارزميات",

            ["python_title"] = "التنفيذ بلغة بايثون",
            ["python_libraries"] = "المكتبات المستخدمة",
            ["python_functions"] = "شرح الدوال",
            ["python_code"] = "الكود المصدري (من الصفر بدون مكتبات تشفير)",
            ["python_verified"] = "تم التحقق من الكود بمتجهات اختبار رسمية — جميع الاختبارات الـ33 ناجحة.",
            ["copy_code"] = "نسخ الكود",
            ["toast_code_copied"] = "تم نسخ كود بايثون إلى الحافظة",
            ["export_pdf"] = "تصدير PDF",
            ["toast_pdf_exported"] = "تم تصدير ملف PDF بنجاح",
            ["toast_pdf_failed"] = "فشل تصدير ملف PDF",

            ["learning_subtitle"] = "دروس منظّمة مع أمثلة وتمارين تفاعلية.",
            ["interactive_exercises"] = "تمارين تفاعلية",

            ["compare_subtitle"] = "قارن بين الخوارزميات من حيث النوع والسرعة والاستخدام وملاحظات الأمان.",
            ["select_algorithms"] = "اختر الخوارزميات",
            ["first_algorithm"] = "الخوارزمية الأولى",
            ["second_algorithm"] = "الخوارزمية الثانية",
            ["compare_property"] = "الخاصية",
            ["compare_type"] = "النوع",
            ["compare_security"] = "الأمان",
            ["compare_key_type"] = "نوع المفتاح",
            ["compare_main_use"] = "الاستخدام الرئيسي",
            ["compare_reversible"] = "قابلة للعكس",
            ["compare_notice"] = "ملاحظة",
            ["yes"] = "نعم",
            ["no"] = "لا",
            ["no_key"] = "بدون مفتاح",

            ["history_title"] = "سجل العمليات",
            ["history_subtitle"] = "بيانات وصفية لعمليات الجلسة فقط. لا يُخزَّن النص الحساس.",
            ["operations"] = "العمليات",

            ["settings_subtitle"] = "تحكم في المظهر واللغة والسجل وبيانات الجلسة.",
            ["security_note"] = "يخزن السجل البيانات الوصفية فقط: الوقت، الخوارزمية، العملية، الحالة، الأطوال، وزمن التنفيذ.",

            ["about_tagline"] = "منصة تفاعلية لتعلم وتجربة التشفير",
            ["about_version"] = "الإصدار",
            ["about_developer"] = "المطور",
            ["about_technology"] = "التقنية",
            ["about_purpose"] = "الغرض التعليمي",
            ["about_purpose_text"] = "تعليم أساسيات التشفير وسلوك الخوارزميات والتحقق من الصحة والفصل الآمن بين العروض التعليمية والأمان الإنتاجي.",
            ["about_license"] = "الترخيص"
        }
    };

    public string Language { get; private set; } = "en";
    public bool IsRightToLeft => string.Equals(Language, "ar", StringComparison.OrdinalIgnoreCase);

    public void SetLanguage(string language)
    {
        Language = _resources.ContainsKey(language) ? language : "en";
        CultureInfo.CurrentUICulture = new CultureInfo(Language == "ar" ? "ar-YE" : "en-US");
    }

    public string T(string key)
    {
        return _resources.TryGetValue(Language, out var current) && current.TryGetValue(key, out var value)
            ? value
            : _resources["en"].TryGetValue(key, out var english) ? english : key;
    }
}